// This file is regenerated by `npm run db:types` after schema migrations apply.
// Placeholder until first migration is applied.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
